<?php

$cfg = require __DIR__ . '/../vendor/mediawiki/mediawiki-phan-config/src/config.php';

$cfg['suppress_issue_types'] = $cfg['suppress_issue_types'] ?? [];

// NS_STORY is generated by the NS config in extension.json
// but phan is probably looking for `define( 'NS_STORY', ... )` and it can't find it
$cfg['suppress_issue_types'][] = "PhanUndeclaredConstant";

return $cfg;
